POST  http://localhost:9000/login 
Content-Type: application/json 

{
    "email":"shwetha@gmail.com",
    "password":"Shwetha@123"
}

###

GET http://localhost:9000/landing
Authorization:eyJhbGciOiJIUzI1NiJ9.c2h3ZXRoYUBnbWFpbC5jb20.PjRGjq1amevzh2hKEKt8DqMLkUqezowXXygPTD-6JY4